### ISSUE TITLE
In Network Topology could each node clickable ?

### ISSUE THREAD

**Issue by pipiche38** [zigbeefordomoticz/Domoticz-Zigbee-UI#10]
Would it be possible to have each node of the Topology diagram clickable (or when leaving the cursor on a node, we got a pop-up with details on the node itself ) ?

**Comment by ben33880** [comment]
yes its possible.
what do u  want to show ?

**Comment by ben33880** [comment]
https://codepen.io/jcrogers/pen/XoMvpd?editors=0010

**Comment by pipiche38** [comment]
To show would be:
ZDeviceName
Health
RSSI

Which are available with zDevice-name

**Comment by ben33880** [comment]
done
